FROM python:3.9-alpine

ENV CELERY_BROKER_URL pyamqp://guest:guest@localhost:5672/
ENV CELERY_RESULT_BACKEND rpc://
ENV C_FORCE_ROOT true

COPY requirements.txt /tmp/requirements.txt

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -U setuptools pip
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /worker

# Specify the command to run on container start
CMD ["celery", "-A", "multiply", "worker", "--loglevel=info", "-Q", "queue_multiply"]